### PR TITLE
Added preliminary MiniRun5 script that combines merged and unmerged hits with new backtracking methods for the latter.

### PR DESCRIPTION
**Pull request by rdiurba**

### CODE REVIEW

**Comment by jback08** [comment]
Overall changes look OK, but I would like to understand the script name choices before merging.

Do we want to rename the modified `h5_to_root_ndlarflow.py` to `h5_to_root_ndlarflow_minirun4.py` if this the "final" version for MiniRun4 formats? 

Likewise, do we want to use `h5_to_root_ndlarflow.py` instead of `h5_to_root_ndlarflow_minirun5.py` if this will be used for MiniRun5 and beyond? Or will this new script only be valid for MiniRun5, in which case the filename is OK and the `h5_to_root_ndlarflow.py` won't be needed?

**Comment by rdiurba** [comment]
I do not know. MiniRun5 will likely take time. Maybe it is better to do as you say to keep versioning similar, I will change .py->minirun4.py and minirun5.py->.py.

**Comment by jback08** [comment]
The file `h5_to_root_ndlarflow_minirun5.py` is now an exact copy of `h5_to_root_ndlarflow.py` and so the former should be removed using `git rm h5_to_root_ndlarflow_minirun5.py`. I can then merge this.

**Comment by rdiurba** [comment]
Apologies. Did the cleanup.

**Comment by jback08** [comment]
Is there a reason why the `minirun3` script was deleted? I guess these runs are not used any more? 

Even so, I was thinking of keeping the "evolution" of the run scripts (from Run3) so that we can keep a history of the various changes, with the latest version always called `h5_to_root_ndlarflow`. In the future, we may want to understand differences between `RunX`, `RunY` and `RunZ` and if the `RunX` script is deleted then we can't easily compare them unless we look at the git history.

**Comment by rdiurba** [comment]
MiniRun3 is identical but the final_hit backtracking required one additional step. I have added the functions that do that back into MiniRun4, but they are basically identical. Some names may be changed in the h5 file, but that is the only difference. MiniRun3 has not been used for months and the dataset is so small to be meaningless.

**Pull request merged**
